import json
import os
import secrets
import sys
from pathlib import Path

from pydantic import BaseModel
from pydantic_settings import BaseSettings, SettingsConfigDict

from core.platform_paths import default_data_dir

APP_NAME = "Cadence"


def _is_packaged() -> bool:
    return bool(os.environ.get("CADENCE_PACKAGED")) or getattr(sys, "frozen", False)


def _get_data_dir() -> str:
    """Per-user data directory (database, settings, work files)."""
    override = os.environ.get("CADENCE_DATA_DIR")
    if override:
        return override
    return default_data_dir(APP_NAME)


def _default_library_dir() -> str:
    return str(Path.home() / "Music" / APP_NAME)


class Settings(BaseSettings):
    """Process-level settings, set by Electron through environment variables."""

    backend_port: int = 8321
    ffmpeg_path: str = os.environ.get("FFMPEG_PATH", "ffmpeg")
    # Shared secret generated by Electron on every launch. Every request must carry it.
    cadence_token: str = ""
    data_dir: str = _get_data_dir()

    model_config = SettingsConfigDict(env_prefix="", env_file=".env", extra="ignore")

    @property
    def work_dir(self) -> str:
        return os.path.join(self.data_dir, "work")

    @property
    def db_path(self) -> str:
        return os.path.join(self.data_dir, "cadence.db")

    @property
    def prefs_path(self) -> str:
        return os.path.join(self.data_dir, "preferences.json")


settings = Settings()
if not settings.cadence_token:
    # Standalone dev run without Electron: generate one so the API is never open.
    settings.cadence_token = secrets.token_urlsafe(32)
    print(f"[Backend] No CADENCE_TOKEN set; generated one for this run: {settings.cadence_token}")


# "original" keeps the downloaded audio as it is (no re-encode); see exporter.original_format.
AUDIO_FORMATS = ("mp3", "flac", "m4a", "opus", "original")
# Bumped when a saved preference needs upgrading on load (see load_preferences).
PREFS_VERSION = 2


class Preferences(BaseModel):
    """User preferences, editable from the Settings page and persisted to disk."""

    library_dir: str = _default_library_dir()
    # "library": always save into library_dir. "ask": pick a folder every time you save.
    save_mode: str = "library"
    # Show the saved songs in Explorer when saving finishes.
    open_when_done: bool = True
    # YouTube sign-in for age-restricted videos and "confirm you're not a bot" checks:
    # "" (none), a browser to read cookies from ("firefox", "chrome", "edge", "brave"),
    # or "file" to use cookies_file (a cookies.txt export).
    cookies_from: str = ""
    cookies_file: str = ""
    # Proxy for YouTube, e.g. "http://host:8080" or "socks5://127.0.0.1:1080". Empty = none.
    proxy: str = ""
    # Lyrics from LRCLIB when saving: "off", "embed" (in the song's tags) or "lrc"
    # (embedded, plus a synced .lrc file next to each song).
    lyrics: str = "off"
    # Crop wide video thumbnails to a square cover, like an album's.
    square_cover: bool = True
    # Write an .m3u8 playlist next to the songs of each album or collection.
    write_playlist: bool = True
    # Keep downloaded source audio after saving, so a split can be saved again.
    keep_downloads: bool = True
    # Name songs found from the audio (no tracklist) by fingerprint, via AcoustID.
    identify_songs: bool = False
    acoustid_key: str = ""
    # Tidy song/album names with Claude after analysis (sends only text, never audio).
    tidy_names: bool = False
    anthropic_api_key: str = ""
    # How many splits are downloaded and analysed at the same time (1-4).
    parallel_splits: int = 2
    audio_format: str = "mp3"
    # kbps for lossy formats; ignored for flac
    audio_bitrate: int = 320
    # Fade applied at each cut edge to remove clicks, in milliseconds.
    edge_fade_ms: int = 10
    # Remove silence at the start and end of each saved song (a short pad is kept).
    trim_silence: bool = True
    # Longer fades at the start and end of each saved song, in seconds (0 = off).
    song_fade_in_s: float = 0.0
    song_fade_out_s: float = 0.0
    # Even out loudness: "off", "tags" (ReplayGain tags, audio unchanged) or
    # "normalize" (one fixed gain per song to reach loudness_target).
    loudness: str = "off"
    loudness_target: float = -14.0
    # How far a cut may move to land on the gap between songs, in seconds.
    # Tracklist timestamps are often 3-4 s off, so this needs room.
    snap_window_s: float = 5.0
    artist_template: str = "Artists/{artist}/{artist} - {title}"
    album_template: str = "Albums/{album}{year_suffix}/{track:02} - {title}"
    collection_template: str = "Collections/{collection}/{track:02} - {title}"
    single_template: str = "Singles/{title}"
    # The welcome screen was completed (or skipped because Cadence was already in use).
    onboarded: bool = False
    version: int = PREFS_VERSION


def load_preferences() -> Preferences:
    try:
        with open(settings.prefs_path, "r", encoding="utf-8") as f:
            data = json.load(f)
        # A settings file from before the welcome screen existed: Cadence is already set up.
        data.setdefault("onboarded", True)
        if data.get("version", 1) < 2:
            # ±2 s was the old default and too narrow to reach the real gap between songs.
            if data.get("snap_window_s") == 2.0:
                data["snap_window_s"] = 5.0
            data["version"] = PREFS_VERSION
        return Preferences(**data)
    except (OSError, ValueError, TypeError):
        return Preferences()


def save_preferences(prefs: Preferences) -> None:
    os.makedirs(os.path.dirname(settings.prefs_path), exist_ok=True)
    tmp = settings.prefs_path + ".tmp"
    with open(tmp, "w", encoding="utf-8") as f:
        json.dump(prefs.model_dump(), f, indent=2)
    os.replace(tmp, settings.prefs_path)
